[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[menu]
  after = [
    { name = 'GitHub', url = 'https://github.com/czdm75', weight = 10 },
    { name = 'Theme', url =  'https://themes.gohugo.io/hugo-book/', weight = 20 }
  ]

[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookDateFormat = '2006-01-02'
  BookComments = false

[markup]
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1

