[tools]
pre-commit = "latest"
typst = "latest"
typstyle = "latest"
uv = "latest"

[tasks.build]
description = "Compile the whole site"
run = "typst compile --features bundle,html --format bundle main.typ public"
